#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export CLI_COMMON_CORE_DEBUG=1
  shift
fi

if [ -n "$CLI_COMMON_CORE_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "cli-common-core: $*"
    fi
  } >&2
  exit 1
}


READLINK=$(type -p greadlink readlink 2>/dev/null | head -1)
[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$PWD"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

if [ -z "${CLI_COMMON_CORE_ROOT}" ]; then
  CLI_COMMON_CORE_ROOT="${HOME}/.cli-common-core"
else
  CLI_COMMON_CORE_ROOT="${CLI_COMMON_CORE_ROOT%/}"
fi
export CLI_COMMON_CORE_ROOT

if [ -z "${CLI_COMMON_CORE_DIR}" ]; then
  CLI_COMMON_CORE_DIR="$PWD"
else
  [[ $CLI_COMMON_CORE_DIR == /* ]] || CLI_COMMON_CORE_DIR="$PWD/$CLI_COMMON_CORE_DIR"
  cd "$CLI_COMMON_CORE_DIR" 2>/dev/null || abort "cannot change working directory to \`$CLI_COMMON_CORE_DIR'"
  CLI_COMMON_CORE_DIR="$PWD"
  cd "$OLDPWD"
fi
export CLI_COMMON_CORE_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
export PATH="${bin_path}:${PATH}"

shopt -u nullglob

command="$1"
case "$command" in
"" )
  { cli-common-core---version
    cli-common-core-help
  } | abort
  ;;
-v | --version )
  exec cli-common-core---version
  ;;
-h | --help )
  exec cli-common-core-help
  ;;
* )
  command_path="$(command -v "cli-common-core-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ "$command" == "shell" ]; then
      abort "shell integration not enabled. Run \`cli-common-core init' for instructions."
    else
      abort "no such command \`$command'"
    fi
  fi

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "cli-common-core help \"$command\""
    else
      exec cli-common-core-help "$command"
    fi
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
